#!/bin/sh
set -e
echo "==> Running unit tests..."
cd "$(git rev-parse --show-toplevel)"
swift test
echo "==> Checking format..."
swift-format lint --recursive --strict Sources/ Tests/ UITests/
echo "==> Running lint..."
swiftlint lint --strict --config .swiftlint.yml
