#!/usr/bin/env bash
set -euo pipefail

SCREENSHOTS_DIR="$1"
BASE_URL="$2"

title_case() {
    echo "$1" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2); print}'
}

label_for() {
    local filename="$1"
    local name="${filename%.png}"
    local prefix
    prefix=$(echo "$name" | cut -d'-' -f1)
    local rest
    rest=$(echo "$name" | cut -d'-' -f2-)

    case "$prefix" in
        settings)
            echo "Settings — $(title_case "$rest")"
            ;;
        onboarding)
            echo "Setup Wizard — $(title_case "$rest")"
            ;;
        *)
            title_case "$name"
            ;;
    esac
}

ORDER=(
    onboarding-welcome.png
    onboarding-shell.png
    onboarding-tools.png
    onboarding-status-line.png
    onboarding-cli-flags.png
    onboarding-profiles.png
    empty-state.png
    new-tab-sheet.png
    new-tab-sheet-filled.png
    main-window-tab.png
    new-pane-sheet.png
    new-pane-agent-control.png
    split-panes.png
    pane-scrollback-menu.png
    existing-worktree-prompt.png
    worktree-cleanup-alert.png
    reordered-tabs-and-panes.png
    pane-status-indicators.png
    notification-sidebar.png
    focused-pane.png
    settings-panes.png
    settings-agent-control.png
    settings-notifications.png
    settings-profiles.png
    settings-tools.png
    settings-shortcuts.png
    settings-status-line.png
    settings-debug.png
    trace-dashboard.png
    trace-waterfall.png
    invariant-dashboard.png
)

in_array() {
    local needle="$1"; shift
    for item in "$@"; do [[ "$item" == "$needle" ]] && return 0; done
    return 1
}

PNGS=()
for f in "${ORDER[@]}"; do
    [[ -f "$SCREENSHOTS_DIR/$f" ]] && PNGS+=("$f")
done
while IFS= read -r f; do
    base="$(basename "$f")"
    [[ -n "$base" ]] && ! in_array "$base" "${PNGS[@]}" && PNGS+=("$base")
done < <(ls "$SCREENSHOTS_DIR"/*.png 2>/dev/null | sort)

printf '\n## Example\n\n'

COUNT=${#PNGS[@]}
COLS=2
i=0
while [ "$i" -lt "$COUNT" ]; do
    header="|"
    sep="|"
    images="|"
    for j in $(seq 0 $(( COLS - 1 ))); do
        idx=$(( i + j ))
        if [ "$idx" -lt "$COUNT" ]; then
            png="${PNGS[$idx]}"
            lbl=$(label_for "$png")
            name="${png%.png}"
            header+=" $lbl |"
            sep+="---|"
            images+=" ![$name]($BASE_URL/$png) |"
        else
            header+="  |"
            sep+="---|"
            images+="  |"
        fi
    done

    echo "$header"
    echo "$sep"
    echo "$images"
    echo ""

    i=$(( i + COLS ))
done

printf '*Auto-generated by `make pr-screenshots`*\n'
