#!/usr/bin/env bash
# Render the ## Example markdown section from screenshots/*.png
# Usage: render-example-section.sh <screenshots-dir> <gist-base-url>
set -euo pipefail

SCREENSHOTS_DIR="$1"
BASE_URL="$2"

title_case() {
    echo "$1" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2); print}'
}

label_for() {
    local filename="$1"
    local name="${filename%.png}"
    local prefix
    prefix=$(echo "$name" | cut -d'-' -f1)
    local rest
    rest=$(echo "$name" | cut -d'-' -f2-)

    case "$prefix" in
        settings)
            echo "Settings — $(title_case "$rest")"
            ;;
        onboarding)
            echo "Setup Wizard — $(title_case "$rest")"
            ;;
        *)
            title_case "$name"
            ;;
    esac
}

PNGS=()
while IFS= read -r f; do
    [[ -n "$f" ]] && PNGS+=("$(basename "$f")")
done < <(ls "$SCREENSHOTS_DIR"/*.png 2>/dev/null | sort)

printf '\n## Example\n\n'

COUNT=${#PNGS[@]}
i=0
while [ "$i" -lt "$COUNT" ]; do
    row_pngs=()
    for j in 0 1 2; do
        idx=$(( i + j ))
        if [ "$idx" -lt "$COUNT" ]; then
            row_pngs+=("${PNGS[$idx]}")
        fi
    done

    header="|"
    sep="|"
    images="|"
    for png in "${row_pngs[@]}"; do
        lbl=$(label_for "$png")
        name="${png%.png}"
        header+=" $lbl |"
        sep+="---|"
        images+=" ![$name]($BASE_URL/$png) |"
    done

    echo "$header"
    echo "$sep"
    echo "$images"
    echo ""

    i=$(( i + 3 ))
done

printf '*Auto-generated by `make pr-screenshots`*\n'
