#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
WORKTREE_DIR="$SCRIPT_DIR/.."

make -C "$WORKTREE_DIR" screenshots
GIST_ID=$(bash "$SCRIPT_DIR/upload-screenshots.sh" | tail -1)
BASE_URL="https://gist.githubusercontent.com/JustinDFuller/${GIST_ID}/raw"

example_section=$(cat <<MARKDOWN

## Example

| Empty State | New Tab Sheet | New Tab Sheet (Filled) |
|---|---|---|
| ![empty-state]($BASE_URL/empty-state.png) | ![new-tab-sheet]($BASE_URL/new-tab-sheet.png) | ![new-tab-sheet-filled]($BASE_URL/new-tab-sheet-filled.png) |

| Main Window Tab | New Pane Sheet | Split Panes |
|---|---|---|
| ![main-window-tab]($BASE_URL/main-window-tab.png) | ![new-pane-sheet]($BASE_URL/new-pane-sheet.png) | ![split-panes]($BASE_URL/split-panes.png) |

| Pane Status Indicators | Notification Sidebar | PR Merged Alert |
|---|---|---|
| ![pane-status-indicators]($BASE_URL/pane-status-indicators.png) | ![notification-sidebar]($BASE_URL/notification-sidebar.png) | ![pr-merged-alert]($BASE_URL/pr-merged-alert.png) |

| Settings — General | Settings — Profiles | Settings — Tools |
|---|---|---|
| ![settings-general]($BASE_URL/settings-general.png) | ![settings-profiles]($BASE_URL/settings-profiles.png) | ![settings-tools]($BASE_URL/settings-tools.png) |

| Settings — CLI Options | Settings — Worktrees | Settings — Shortcuts |
|---|---|---|
| ![settings-cli-options]($BASE_URL/settings-cli-options.png) | ![settings-worktrees]($BASE_URL/settings-worktrees.png) | ![settings-shortcuts]($BASE_URL/settings-shortcuts.png) |

| Settings — Status Line | Settings — Notifications | Settings — Tracing |
|---|---|---|
| ![settings-status-line]($BASE_URL/settings-status-line.png) | ![settings-notifications]($BASE_URL/settings-notifications.png) | ![settings-tracing]($BASE_URL/settings-tracing.png) |

*Auto-generated by \`make pr-screenshots\`*
MARKDOWN
)

current_body=$(gh pr view --json body --jq '.body')

if echo "$current_body" | grep -q "^## Example"; then
  prefix=$(echo "$current_body" | sed '/^## Example/,$d')
else
  prefix="$current_body"
fi

new_body="${prefix}${example_section}"

gh pr edit --body "$new_body"
echo "PR body updated with screenshots under ## Example."
