#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
WORKTREE_DIR="$SCRIPT_DIR/../.agent-session-manager/worktrees/screenshots"
GIST_ID_FILE="$SCRIPT_DIR/../.screenshots-gist-id"

make -C "$WORKTREE_DIR" screenshots
GIST_ID=$(bash "$SCRIPT_DIR/upload-screenshots.sh" | tail -1)
BASE_URL="https://gist.githubusercontent.com/JustinDFuller/${GIST_ID}/raw"

example_section=$(cat <<MARKDOWN

## Example

| Empty State | Main Window |
|---|---|
| ![empty-state]($BASE_URL/empty-state.png) | ![main-window-tab]($BASE_URL/main-window-tab.png) |

| New Pane Sheet | Settings — General |
|---|---|
| ![new-pane-sheet]($BASE_URL/new-pane-sheet.png) | ![settings-general]($BASE_URL/settings-general.png) |

| Settings — Notifications | |
|---|---|
| ![settings-notifications]($BASE_URL/settings-notifications.png) | |

*Auto-generated by \`make pr-screenshots\`*
MARKDOWN
)

current_body=$(gh pr view --json body --jq '.body')

if echo "$current_body" | grep -q "^## Example"; then
  prefix=$(echo "$current_body" | sed '/^## Example/,$d')
else
  prefix="$current_body"
fi

new_body="${prefix}${example_section}"

gh pr edit --body "$new_body"
echo "PR body updated with screenshots under ## Example."
